### ISSUE TITLE
There is a error when i set a swf file: the swf2js cannot parse the sound.

### ISSUE THREAD

**Issue by sharh** [ienaga/swf2js#16]
a file link:[http://file.eebbk.net/server-socialadmin/cloudIDN/social_admin/2017/03/15/105752205_7d3a2f00d23cec8d.swf](url)

**Comment by ienaga** [comment]
thank you sample file!
I will look it up and see!

**Comment by sharh** [comment]
Well, If you hava any idea or find the reason, please repeat me. By the way, could you support some APIs, like get the captions?Or just I don't find it?The document is confused for me.
