### ISSUE TITLE
Support background transparency

### ISSUE THREAD

**Issue by vikbez** [ienaga/swf2js#3]
Thanks for your work this is really great !

Could you add support for flash files with transparent background ?
example file: http://www.cjoint.com/data/FHkkjnKNR4R_TransparentBG.swf

**Comment by ienaga** [comment]
@vikbez 

Thank for your request!

Added the ability!!


# sample code 

```html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1.0" />
    <title>background transparency</title>
    <script type="text/javascript" src="swf2js.js"></script>
</head>
<body style="margin: 0; padding: 0; background-color: #000000;">
<script type="text/javascript">

    // _root
    var _root = swf2js.createRootMovieClip(1024, 768, 120);

    // stage setting
    var stage = _root.getStage();
    stage.backgroundColor = null;

    // swf load
    _root.loadMovie("./FHkkjnKNR4R_TransparentBG.swf");

    // action
    _root.addEventListener("enterFrame", function(){
        if (this.getCurrentFrame() === 349) {
            this.gotoAndPlay(215);
        }
    });

</script>
</body>
</html>
```

I'm afraid my expressions may be rude or hard to read, because I'm not so good at English.

**Comment by vikbez** [comment]
Thanks for very fast response and sample !

There is still a problem because the background stays black 
(try setting background-color: #b7d;)

**Comment by karkinge** [comment]
Yes, thank you so much for trying to solve the issue !

We tried setting the stage.backgroundColor to "transparent" or "rgba(0,0,0,0)" , but it causes repaint issues during the animation. Maybe just a "clear" frame is missing somewhere ?

**Comment by vikbez** [comment]
Done a PR, don't know if it's the right way to do it : 
https://github.com/ienaga/swf2js/pull/4

**Comment by ienaga** [comment]
@karkinge

Thank you!
Indeed!! "transparent" was this!

**Comment by ienaga** [comment]
@vikbez 

Thank you PR!
I have received a very big hint .

update 0.6.21

By all means, please try using.

**Comment by ienaga** [comment]
a little added.

`stage.backgroundColor` will start in "null" or "transparent".

# sample code2

```html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1.0" />
    <title>background transparency</title>
    <script type="text/javascript" src="swf2js.js"></script>
</head>
<body style="margin: 0; padding: 0; background-color: #000000;">
<script type="text/javascript">

    // _root
    var _root = swf2js.createRootMovieClip(1024, 768, 120);

    // stage setting
    var stage = _root.getStage();
    stage.backgroundColor = "transparent";

    // swf load
    _root.loadMovie("./FHkkjnKNR4R_TransparentBG.swf");

    // action
    _root.addEventListener("enterFrame", function(){
        if (this.getCurrentFrame() === 349) {
            this.gotoAndPlay(215);
        }
    });

</script>
</body>
</html>
```

**Comment by vikbez** [comment]
:+1: :+1: :+1: 

works perfect

**Comment by ienaga** [comment]
@vikbez

It has been simplified.

```js
swf2js.load("./FHkkjnKNR4R_TransparentBG.swf", { bgcolor: "transparent" });
```
var 0.7.3

**Comment by vikbez** [comment]
wow ! great !
thanks 😄
